<?php



/**
 * Skeleton subclass for performing query and update operations on the 'sf_plop_shop_cart_product' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.4-dev on:
 *
 * jeu. 26 janv. 2012 15:21:58 CET
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.plugins.sfPlopShopPlugin.lib.model
 */
class sfPlopShopCartProductPeer extends BasesfPlopShopCartProductPeer {

} // sfPlopShopCartProductPeer
