<?php



/**
 * Skeleton subclass for performing query and update operations on the 'sf_plop_shop_order' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.4-dev on:
 *
 * jeu. 26 janv. 2012 11:18:58 CET
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.plugins.sfPlopShopPlugin.lib.model
 */
class sfPlopShopOrderPeer extends BasesfPlopShopOrderPeer
{
	public static function retrieveOneInProcessByUserId($id = null)
	{
		$orders = self::retrieveInProcessByUserId($id);
		if (isset($orders[0]))
			return $orders[0];
	}
	
	public static function retrieveInProcessByUserId($id = null)
	{
		if (!$id)
			return;
		
		return sfPlopShopOrderQuery::create()
			->filterByInProcess(true)
			->filterByUserId($id)
			->find()
		;
	}

	public static function retrieveByUserId($id = null)
	{
		if (!$id)
			return;
		
		return sfPlopShopOrderQuery::create()
			->filterByUserId($id)
			->find()
		;
	}

} // sfPlopShopOrderPeer
