<?php



/**
 * Skeleton subclass for representing a row from the 'sf_plop_shop_product' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.4-dev on:
 *
 * jeu. 26 janv. 2012 11:18:57 CET
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.plugins.sfPlopShopPlugin.lib.model
 */
class sfPlopShopProduct extends BasesfPlopShopProduct {

  public function __toString()
  {
    return $this->getName();
  }

  public function getFullDescription()
  {
    return
      ($this->getTitle() ? $this->getTitle() : $this->getName())
      . ($this->getPrice()
        ? (' (' . $this->getCompletePrice()
          . ($this->isRecurrent() ? ' / ' . $this->getDurationUnit() : null
        ) . ')')
        : null)
    ;
  }

  public function getPackProducts()
  {
    return sfPlopShopProductQuery::create()
      ->usesfPlopShopProductPackRelatedByProductIdQuery()
        ->filterByPackId($this->getId())
      ->endUse()
      ->find()
    ;
  }

  public function isPack()
  {
    return $this->getIsPack();
  }

  public function getTaxRate()
  {
    return $this->getTax()->getRate();
  }

  public function getCompletePrice()
  {
    return $this->getNetPrice() . ' ' . $this->getCurrency()->getCode();
  }

  public function getCompletePriceWithDuration()
  {
    return $this->getCompletePrice() 
      . ($this->isRecurrent() ? ' / ' . $this->getDurationUnit() : null);
  }

  public function getTax()
  {
    return $this->getsfPlopShopTax();
  }
  
  public function getCurrency()
  {
    return $this->getsfPlopShopCurrency();
  }
  
  public function isRecurrent()
  {
    return $this->getIsRecurrent();
  }
  
  public function getDuration()
  {
    return $this->getsfPlopShopDuration();
  }
  
  public function getDurationUnit()
  {
    return preg_replace('/([0-9]+)/', '', $this->getsfPlopShopDuration());
  }
  
} // sfPlopShopProduct
