<?php



/**
 * Skeleton subclass for performing query and update operations on the 'sf_plop_shop_category_i18n' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.5-dev on:
 *
 * mer. 08 févr. 2012 15:53:47 CET
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.plugins.sfPlopShopPlugin.lib.model
 */
class sfPlopShopCategoryI18nQuery extends BasesfPlopShopCategoryI18nQuery {

} // sfPlopShopCategoryI18nQuery
