<?php



/**
 * Skeleton subclass for representing a row from the 'sf_plop_shop_tax' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.4-dev on:
 *
 * jeu. 26 janv. 2012 11:18:57 CET
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.plugins.sfPlopShopPlugin.lib.model
 */
class sfPlopShopTax extends BasesfPlopShopTax {

  public function __toString()
  {
    return $this->getRate();
  }
  
  public function getDescription()
  {
    return $this->getName() . ' - ' . $this->getRate();
  }

} // sfPlopShopTax
