generator:
  class: sfPropelGenerator
  param:
    model_class:           sfPlopShopCategory
    theme:                 admin15
    non_verbose_templates: true
    with_show:             false
    singular:              sfPlopShopCategory
    plural:                sfPlopShopCategorys
    route_prefix:          sf_plop_shop_category
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
        title:             Categories list
      filter:  ~
      form:    ~
      edit:
        title:             Editing category "%%name%%"

      new:
        title:             New category
